platform :ios, '15.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'Analytics', '~> 4.0'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end

post_install do |installer|
  # SEGReachability.m imports the BSD header netinet6/in6.h without using
  # anything from it. Newer Xcode toolchains reject the import as a private
  # header from outside its module, so drop the dead import.
  reachability_path = File.join(__dir__, 'Pods/Analytics/Segment/Classes/SEGReachability.m')
  if File.exist?(reachability_path)
    contents = File.read(reachability_path)
    patched = contents.sub("#import <netinet6/in6.h>\n", '')
    File.write(reachability_path, patched) if patched != contents
  end
end
